#!/bin/sh
alias ka="killall" \
	mkd="mkdir -pv" \
    a="sudo apt" \
	g="git" \
	v="$EDITOR" \
    sv="sudo $EDITOR" \
	ls="ls -hN --color=auto --group-directories-first" \
	grep="grep --color=auto" \
	diff="diff --color=auto" \
    ghci="stack ghci" \
    in='task add +in' \
    chore='task project:Chores-$(date +%d-%m-%Y)' \
    tt='taskwarrior-tui'

command -v nvim >/dev/null && alias vim="nvim" vimdiff="nvim -d" # Use neovim for vim if present.

vf() { fzf | xargs -r -I % $EDITOR % ;}
